[project]
name = "visit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "playwright>=1.55.0",
    "requests>=2.32.5",
]
